// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIvfxdkKXl2f0AfQYxe1GwCJ51ZZwmeuA',
    appId: '1:966326210845:web:8dcc00749d74f3794c51f4',
    messagingSenderId: '966326210845',
    projectId: 'fluttertest-b9880',
    authDomain: 'fluttertest-b9880.firebaseapp.com',
    databaseURL: 'https://fluttertest-b9880-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-b9880.appspot.com',
    measurementId: 'G-3VE1V6KF7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1aDjgIWgN9G3WlodF92sTYouf4uj5rfI',
    appId: '1:966326210845:android:7f0b0826d157589a4c51f4',
    messagingSenderId: '966326210845',
    projectId: 'fluttertest-b9880',
    databaseURL: 'https://fluttertest-b9880-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-b9880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9pAezHRL_q3sJcnMFE2SWfeEQE5gq6Eo',
    appId: '1:966326210845:ios:fbdccf4dc79acb9d4c51f4',
    messagingSenderId: '966326210845',
    projectId: 'fluttertest-b9880',
    databaseURL: 'https://fluttertest-b9880-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-b9880.appspot.com',
    iosBundleId: 'com.fahamin.todolistFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9pAezHRL_q3sJcnMFE2SWfeEQE5gq6Eo',
    appId: '1:966326210845:ios:6a949c16de18359c4c51f4',
    messagingSenderId: '966326210845',
    projectId: 'fluttertest-b9880',
    databaseURL: 'https://fluttertest-b9880-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-b9880.appspot.com',
    iosBundleId: 'com.fahamin.todolistFlutter.RunnerTests',
  );
}
